source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'ZBUtilities'
pod 'RATreeView'
pod 'HockeySDK'
pod 'HMSegmentedControl'