source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'ZBUtilities'
pod 'RATreeView'
pod 'HMSegmentedControl'
pod 'AFNetworking', '~> 1.3.4'
#pod 'AFNetworking', '~> 2.5.0'
#pod 'JSONKit'
pod 'ZBarSDK'
pod 'SSKeychain'
pod 'TouchJSON'
pod 'SDWebImage', '~> 3.7.1'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'XHRefreshControl', '~> 3.8'
pod 'SSCommon-Utilities', :git => 'https://github.com/Seven-Sun/SSCommon-Utilities.git'

target 'SmartHomePro' do
    
    pod 'SSCommon-Utilities', :git => 'https://github.com/Seven-Sun/SSCommon-Utilities.git'
    pod 'AFNetworking', '~> 1.3.4'
    pod 'ZBUtilities'
    pod 'ZBarSDK'
    pod 'SSKeychain'
    pod 'TouchJSON'
	pod 'PhotoZoom', '~> 0.0.2'
    pod 'ZBUtilities'
end
