source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'ZBUtilities'
pod 'RATreeView'
pod 'HMSegmentedControl'
pod 'AFNetworking', '~> 1.3.4'
#pod 'AFNetworking', '~> 2.5.0'
#pod 'JSONKit'
pod 'ZBarSDK'
pod 'SSKeychain'
pod 'TouchJSON'
pod 'SDWebImage', '~> 3.7.1'
pod 'UIAlertView-Blocks', '~> 1.0'
